# Generated by Django 6.0.3 on 2026-03-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carpool", "0002_transaction_wallet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="decriptions",
            new_name="description",
        ),
    ]
